data:
  dataset: "imagenet100"
  num_workers: 4

model:
  name: "deit_small"                     # or deit_tiny, deit_base
  num_classes: 100
  img_size: 224
  pretrained: true

quantization:
  method: "adaptive_log"
  momentum: 0.1
  bits: 8
  threshold: 100
  adaptive_threshold: true
  target_second_word_ratio: 0.97        # Keep your successful ratio
  switch_iteration: 8000
  eps: 0.000001                         # Keep the safer epsilon

sparsification:
  enabled: false

training:
  num_epochs: 100
  lr: 0.0001                           # Conservative LR for quantized transformers
  weight_decay: 0.05                   # Higher weight decay for transformers  
  early_stop_patience: 50
  log_interval: 100
  batch_size: 32                       # Smaller due to memory constraints
  gradient_accumulation_steps: 8       # Effective batch size = 256

system:
  device: "cuda:0"
  work_dir: "./output_imagenet_deit_small_log"
  seed: 42