# configs/vit_small_with_sparsification.yaml
data:
  dataset: "cifar10"
  batch_size: 32
  num_workers: 4

model:
  name: "vit_small"
  num_classes: 10
  img_size: 32
  pretrained: true

quantization:
  method: "adaptive_log"
  momentum: 0.1
  bits: 8
  threshold: 100
  adaptive_threshold: true
  target_second_word_ratio: 0.25
  switch_iteration: 5000000

sparsification:
  enabled: true
  method: "magnitude"
  target_ratio: 0.3
  apply_after_epoch: 2
  cost_penalty: 2.0

training:
  num_epochs: 150  # Will auto-adjust if needed
  finetune_epochs: 20
  lr: 0.0001
  weight_decay: 0.0001
  early_stop_patience: 10
  log_interval: 100

system:
  device: "cuda:0"
  work_dir: "./output"  # Will auto-adjust to "./output_log_sparse50"
  seed: 42