data:
  dataset: "imagenet100"
  num_workers: 4

model:
  name: "resnet18"
  num_classes: 100
  img_size: 224
  pretrained: true

quantization:
  method: "adaptive_log"
  momentum: 0.1
  bits: 8
  threshold: 100
  adaptive_threshold: true
  target_second_word_ratio: 0.15
  switch_iteration: 8000
  eps: 0.00000001

sparsification:
  enabled: false

training:
  num_epochs: 100
  lr: 0.01
  weight_decay: 0.0001
  early_stop_patience: 50
  log_interval: 100
  batch_size: 64
  gradient_accumulation_steps: 1

system:
  device: "cuda:0"
  work_dir: "./output_imagenet_resnet18_log_15"
  seed: 42